export const keyNames = {
	address1: 'Address 1',
	address2: 'Address 2',
	address3: 'Address 3',
	adminUserId: 'Admin User ID',
	ability_one_sku: 'Ability One SKU',
	change_pw: 'Change password',
	gp_account: 'GP account',
	gp_price_sheet: 'GP price sheet ID',
	green: 'Contains recycled content',
	green_attributes: 'Recycled content %',
	id: 'ID',
	img_url: 'Image URL',
	mfg_part_num: 'Mfr. part #',
	prop65: 'Prop 65',
	prop65warning: 'Prop 65 warning',
	punchin_identity: 'Punchin identity',
	qty: 'Quantity',
	sku: 'SKU',
	unspsc: 'UNSPSC',
	uomdesc: 'UoM Desc.',
	uomid: 'UoM ID',
	uomqty: 'UoM quantity',
	upc: 'UPC',
};
